### ISSUE TITLE
Assembly Scanning broken in v3

### ISSUE THREAD

**Issue by buvinghausen** [Particular/NServiceBus.Storage.MongoDB#198]
When I remove the Mongo package I'm able to startup without the assembly scan issues.  Attached both the error message and stack trace.

Could not enumerate all types for 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
Exceptions:
System.TypeLoadException: Method 'Commit' in type 'NServiceBus.Storage.MongoDB.MongoOutboxTransaction' from assembly 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'Get' in type 'NServiceBus.Storage.MongoDB.OutboxPersister' from assembly 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'Save' in type 'NServiceBus.Storage.MongoDB.SagaPersister' from assembly 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'Subscribe' in type 'NServiceBus.Storage.MongoDB.SubscriptionPersister' from assembly 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task NServiceBus.Persistence.CompletableSynchronizedStorageSession.CompleteAsync()'.
System.TypeLoadException: Method 'TryAdapt' in type 'NServiceBus.Storage.MongoDB.StorageSessionAdapter' from assembly 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'OpenSession' in type 'NServiceBus.Storage.MongoDB.StorageSessionFactory' from assembly 'NServiceBus.Storage.MongoDB, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

at NServiceBus.Hosting.Helpers.AssemblyScanner.AddTypesToResult(Assembly assembly, AssemblyScannerResults results) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs:line 394
at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs:line 115
at NServiceBus.AssemblyScanningComponent.Initialize(Configuration configuration, SettingsHolder settings) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs:line 41
at NServiceBus.HostCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IServiceCollection serviceCollection) in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 17
at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IServiceCollection serviceCollection) in /_/src/NServiceBus.Core/EndpointWithExternallyManagedContainer.cs:line 18

**Comment by SzymonPobiega** [comment]
Hi

Thanks for reporting this. I assume you are using the pre-release version 8 of the NServiceBus? I guess the problem might be caused by these packages not being aligned i.e. in our development process we release new internal pre-release versions of NServiceBus but not all these versions have corresponding downstream releases.

**Comment by adamralph** [comment]
@buvinghausen as @SzymonPobiega says, the current pre-release packages which reference NServiceBus 8.x are not yet ready for consumption and are not all aligned with each other with respect to package reference versions. That is why we have only pushed specific packages to myget (for internal testing), rather than nuget.org.

To avoid these issues, it's best to only consume packages which we publish to nuget.org. If you find issues with the packages that are published to nuget.org, please feel free to raise them here.

**Comment by adamralph** [comment]
FTR, see https://github.com/Particular/NServiceBus/issues/6090#issuecomment-856866086 as a follow-up response.
